products = [
    "Laptop",
    "Smartphone",
    "Headphones",
    "Smartwatch",
    "Tablet",
    "Bluetooth Speaker",
    "Wireless Charger",
    "Gaming Console",
    "External Hard Drive",
    "Keyboard",
    "Mouse",
    "Monitor",
    "Printer",
    "Camera",
    "Tripod",
    "Power Bank",
    "Fitness Tracker",
    "E-Reader",
    "Desktop PC",
    "VR Headset",
    "Gaming Chair",
    "Portable Projector",
    "Webcam",
    "Microphone",
    "Graphics Tablet",
    "Smart Light Bulb",
    "Smart Plug",
    "Electric Scooter",
    "Air Purifier",
    "Coffee Maker",
    "Blender",
    "Dishwasher",
    "Refrigerator",
    "Washing Machine",
    "Oven",
    "Vacuum Cleaner",
    "Electric Kettle",
    "Hair Dryer",
    "Toaster",
    "Food Processor",
    "Pressure Cooker",
    "Water Purifier",
    "Smart Thermostat",
    "Drone",
    "Action Camera",
    "Electric Toothbrush",
    "Hair Straightener",
    "Wi-Fi Router",
    "Soundbar",
    "Smart Doorbell"
]
