products = [
    {"name": "Laptop", "price": 1000, "category": "Electronics"},
    {"name": "Smartphone", "price": 800, "category": "Electronics"},
    {"name": "Headphones", "price": 150, "category": "Electronics"},
    {"name": "Smartwatch", "price": 250, "category": "Electronics"},
    {"name": "Tablet", "price": 500, "category": "Electronics"},
    {"name": "Bluetooth Speaker", "price": 120, "category": "Electronics"},
    {"name": "Wireless Charger", "price": 40, "category": "Electronics"},
    {"name": "Gaming Console", "price": 400, "category": "Electronics"},
    {"name": "External Hard Drive", "price": 100, "category": "Electronics"},
    {"name": "Keyboard", "price": 60, "category": "Electronics"},
    {"name": "Mouse", "price": 40, "category": "Electronics"},
    {"name": "Monitor", "price": 200, "category": "Electronics"},
    {"name": "Printer", "price": 150, "category": "Electronics"},
    {"name": "Camera", "price": 700, "category": "Electronics"},
    {"name": "Tripod", "price": 80, "category": "Electronics"},
    {"name": "Power Bank", "price": 50, "category": "Electronics"},
    {"name": "Fitness Tracker", "price": 100, "category": "Electronics"},
    {"name": "E-Reader", "price": 130, "category": "Electronics"},
    {"name": "Desktop PC", "price": 1200, "category": "Electronics"},
    {"name": "VR Headset", "price": 350, "category": "Electronics"},
    {"name": "Gaming Chair", "price": 180, "category": "Furniture"},
    {"name": "Portable Projector", "price": 300, "category": "Electronics"},
    {"name": "Webcam", "price": 70, "category": "Electronics"},
    {"name": "Microphone", "price": 100, "category": "Electronics"},
    {"name": "Graphics Tablet", "price": 250, "category": "Electronics"},
    {"name": "Smart Light Bulb", "price": 30, "category": "Home Automation"},
    {"name": "Smart Plug", "price": 25, "category": "Home Automation"},
    {"name": "Electric Scooter", "price": 500, "category": "Transportation"},
    {"name": "Air Purifier", "price": 200, "category": "Home Appliances"},
    {"name": "Coffee Maker", "price": 100, "category": "Home Appliances"},
    {"name": "Blender", "price": 80, "category": "Home Appliances"},
    {"name": "Dishwasher", "price": 700, "category": "Home Appliances"},
    {"name": "Refrigerator", "price": 1200, "category": "Home Appliances"},
    {"name": "Washing Machine", "price": 800, "category": "Home Appliances"},
    {"name": "Oven", "price": 600, "category": "Home Appliances"},
    {"name": "Vacuum Cleaner", "price": 150, "category": "Home Appliances"},
    {"name": "Electric Kettle", "price": 50, "category": "Home Appliances"},
    {"name": "Hair Dryer", "price": 40, "category": "Personal Care"},
    {"name": "Toaster", "price": 30, "category": "Home Appliances"},
    {"name": "Food Processor", "price": 150, "category": "Home Appliances"},
    {"name": "Pressure Cooker", "price": 100, "category": "Home Appliances"},
    {"name": "Water Purifier", "price": 200, "category": "Home Appliances"},
    {"name": "Smart Thermostat", "price": 250, "category": "Home Automation"},
    {"name": "Drone", "price": 800, "category": "Electronics"},
    {"name": "Action Camera", "price": 300, "category": "Electronics"},
    {"name": "Electric Toothbrush", "price": 70, "category": "Personal Care"},
    {"name": "Hair Straightener", "price": 60, "category": "Personal Care"},
    {"name": "Wi-Fi Router", "price": 100, "category": "Electronics"},
    {"name": "Soundbar", "price": 200, "category": "Electronics"},
    {"name": "Smart Doorbell", "price": 150, "category": "Home Automation"}
]
