products = [
    {"name": "Laptop", "price": 1000},
    {"name": "Smartphone", "price": 800},
    {"name": "Headphones", "price": 150},
    {"name": "Smartwatch", "price": 250},
    {"name": "Tablet", "price": 500},
    {"name": "Bluetooth Speaker", "price": 120},
    {"name": "Wireless Charger", "price": 40},
    {"name": "Gaming Console", "price": 400},
    {"name": "External Hard Drive", "price": 100},
    {"name": "Keyboard", "price": 60},
    {"name": "Mouse", "price": 40},
    {"name": "Monitor", "price": 200},
    {"name": "Printer", "price": 150},
    {"name": "Camera", "price": 700},
    {"name": "Tripod", "price": 80},
    {"name": "Power Bank", "price": 50},
    {"name": "Fitness Tracker", "price": 100},
    {"name": "E-Reader", "price": 130},
    {"name": "Desktop PC", "price": 1200},
    {"name": "VR Headset", "price": 350},
    {"name": "Gaming Chair", "price": 180},
    {"name": "Portable Projector", "price": 300},
    {"name": "Webcam", "price": 70},
    {"name": "Microphone", "price": 100},
    {"name": "Graphics Tablet", "price": 250},
    {"name": "Smart Light Bulb", "price": 30},
    {"name": "Smart Plug", "price": 25},
    {"name": "Electric Scooter", "price": 500},
    {"name": "Air Purifier", "price": 200},
    {"name": "Coffee Maker", "price": 100},
    {"name": "Blender", "price": 80},
    {"name": "Dishwasher", "price": 700},
    {"name": "Refrigerator", "price": 1200},
    {"name": "Washing Machine", "price": 800},
    {"name": "Oven", "price": 600},
    {"name": "Vacuum Cleaner", "price": 150},
    {"name": "Electric Kettle", "price": 50},
    {"name": "Hair Dryer", "price": 40},
    {"name": "Toaster", "price": 30},
    {"name": "Food Processor", "price": 150},
    {"name": "Pressure Cooker", "price": 100},
    {"name": "Water Purifier", "price": 200},
    {"name": "Smart Thermostat", "price": 250},
    {"name": "Drone", "price": 800},
    {"name": "Action Camera", "price": 300},
    {"name": "Electric Toothbrush", "price": 70},
    {"name": "Hair Straightener", "price": 60},
    {"name": "Wi-Fi Router", "price": 100},
    {"name": "Soundbar", "price": 200},
    {"name": "Smart Doorbell", "price": 150}
]

